# Generated by Django 3.1.2 on 2020-12-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='teachers',
            name='suit',
            field=models.IntegerField(choices=[(1, 'Diamond'), (2, 'Spade'), (3, 'Heart'), (4, 'Club')], default=1),
        ),
    ]
