# Generated by Django 3.1.2 on 2020-12-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20201214_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
